### ISSUE TITLE
OpenTok: HelloWorld Not working with official Account API key and secret Configured

### ISSUE THREAD

**Issue by tejastank** [opentok/Opentok-Python-SDK#113]
As configured API keys and run the helloworld file below bug generated.

How can I resolve it ?

devid@lp-snippetbucket:~/source/snippets/OpenTok/sample/HelloWorld$ python helloworld.py 
Traceback (most recent call last):
  File "helloworld.py", line 10, in <module>
    session = opentok.create_session()
  File "/home/ttrrew/source/snippets/OpenTok/opentok/opentok.py", line 266, in create_session
    raise AuthError('Failed to create session, invalid credentials')
opentok.exceptions.AuthError: Failed to create session, invalid credentials

Even correct keys given, why this issue generated ?

Please guide urgent base in an hour.

**Comment by maikthomas** [comment]
Hi @tejastank,
We have tried this and haven't been able to reproduce the error.
Could you please double check your API key and secret at https://tokbox.com/account/ in the projects section?
Ensure you can generate sessions and tokens there.
Thanks,
Mike

**Comment by sabikla** [comment]
I have the same issue, but work fine in our qa env.

**Comment by aiham** [comment]
@sabikla Please provide more details about your problem with steps to reproduce the issue. Thanks

**Comment by sabikla** [comment]
@aiham I have identified the actual issue and resolved it. 
The problem we faced was :
We have two different servers for QA and UAT, both are using the same API Key and Secret. But the QA environment was working fine and not in UAT. In UAT we encountered **invalid credentials** 

The root cause we identified was the system time in UAT was 1 minute ahead, the auth token generated by your SDK became invalid. we fixed the same by changing the system time. Can you suggest any alternative methods to overcome this issue in future.

**Comment by aiham** [comment]
@sabikla Thanks for the response.

As for suggestions that would depend on your operating system but I would suggest you regularly sync with a public time server. See https://superuser.com/questions/123962/how-can-i-permanently-fix-my-date-synchronize-problem-in-linux

**Comment by tejastank** [comment]
Actually I had done with this, As I remember in home or welcome screen credidential not works, but via other steps I had created credidential than it was worked for me.
